configuration:
  LINK_SPECIFICATION_ID: b229c8c8-101a-4dab-b0b0-7aa2e23d1bc1
  IAM:
    ENABLED: true
    PREFIX: nullplatform-scopes
    ROLE:
      POLICIES:
        - TYPE: inline
          VALUE: |
            {
               "Version":"2012-10-17",
               "Statement":[
                  {
                     "Sid":"AccesoLecturaEscrituraContenido",
                     "Effect":"Allow",
                     "Action":[
                        "s3:GetObject",
                        "s3:PutObject",
                        "s3:DeleteObject",
                        "s3:ListBucket",
                        "s3:GetBucketLocation",
                        "s3:ListAllMyBuckets",
                        "sqs:SendMessage",
                        "sqs:ReceiveMessage",
                        "sqs:DeleteMessage",
                        "sqs:GetQueueAttributes",
                        "sqs:ListQueues",
                        "sns:Publish",
                        "sns:Subscribe",
                        "sns:ListTopics",
                        "dynamodb:GetItem",
                        "dynamodb:BatchGetItem",
                        "dynamodb:PutItem",
                        "dynamodb:UpdateItem",
                        "dynamodb:DeleteItem",
                        "dynamodb:Query",
                        "dynamodb:Scan",
                        "kinesis:PutRecord",
                        "kinesis:PutRecords",
                        "kinesis:GetRecords",
                        "kinesis:DescribeStream",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents",
                        "logs:GetLogEvents",
                        "logs:FilterLogEvents",
                        "logs:DescribeLogGroups",
                        "logs:DescribeLogStreams"
                     ],
                     "Resource":[
                        "arn:aws:s3:::*",
                        "arn:aws:s3:::*/*",
                        "arn:aws:sqs:*:*:*",
                        "arn:aws:sns:*:*:*",
                        "arn:aws:dynamodb:*:*:table/*",
                        "arn:aws:kinesis:*:*:stream/*",
                        "arn:aws:logs:*:*:log-group:*"
                     ],
                     "Condition":{
                        "StringEquals":{
                           "aws:ResourceAccount":"${aws:PrincipalAccount}"
                        }
                     }
                  },
                  {
                     "Action":"sts:AssumeRole",
                     "Effect":"Allow",
                     "Resource":"arn:aws:iam::*:role/tr-spin-card-aggregation-service-backend-java-gradle-*",
                     "Sid":"MSKAccess"
                  }
               ]
            }
  IMAGE_PULL_SECRETS:
    ENABLED: true
    SECRETS:
      - regcred